apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-algorithm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trading-algorithm
  template:
    metadata:
      labels:
        app: trading-algorithm
    spec:
      containers:
        - name: data-ingestion
          image: khalilamouri/data-ingestion:latest
          ports:
            - containerPort: 5000

        - name: strategy
          image: khalilamouri/strategy:latest
          ports:
            - containerPort: 5001

        - name: risk-management
          image: khalilamouri/risk-management:latest
          ports:
            - containerPort: 5002

        - name: visualization
          image: khalilamouri/visualization:latest
          ports:
            - containerPort: 8000

        - name: redis
          image: redis
          ports:
            - containerPort: 6379

        - name: monitoring
          image: grafana/grafana
          ports:
            - containerPort: 3000
---
# Define services for each container
apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-service
spec:
  selector:
    app: trading-algorithm
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: strategy-service
spec:
  selector:
    app: trading-algorithm
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: visualization-service
spec:
  selector:
    app: trading-algorithm
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: trading-algorithm
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
