name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        env:
          DOCKER_IMAGE_PREFIX: yourdockerhubusername
        run: |
          docker build -t $DOCKER_IMAGE_PREFIX/data-ingestion:latest -f data-ingestion/Dockerfile data-ingestion/
          docker push $DOCKER_IMAGE_PREFIX/data-ingestion:latest
          
          docker build -t $DOCKER_IMAGE_PREFIX/strategy:latest -f strategy/Dockerfile strategy/
          docker push $DOCKER_IMAGE_PREFIX/strategy:latest
          
          docker build -t $DOCKER_IMAGE_PREFIX/risk-management:latest -f risk-management/Dockerfile risk-management/
          docker push $DOCKER_IMAGE_PREFIX/risk-management:latest
          
          docker build -t $DOCKER_IMAGE_PREFIX/visualization:latest -f visualization/Dockerfile visualization/
          docker push $DOCKER_IMAGE_PREFIX/visualization:latest

      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ${{ secrets.K8S_USER }}
          key: ${{ secrets.K8S_SSH_KEY }}
          script: |
            kubectl apply -f k8s-deployment.yaml
