name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # This ensures the job runs on your self-hosted runner

    steps:
      # Step 1: Set PowerShell Execution Policy
      - name: Set PowerShell Execution Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
        shell: pwsh

      # Step 2: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and push Docker images
      - name: Build and push Docker images
        env:
          DOCKER_IMAGE_PREFIX: khalilamouri
        run: |
          docker build -t $DOCKER_IMAGE_PREFIX/data-ingestion:latest -f data-ingestion/Dockerfile data-ingestion/
          docker push $DOCKER_IMAGE_PREFIX/data-ingestion:latest
          
          docker build -t $DOCKER_IMAGE_PREFIX/strategy:latest -f strategy/Dockerfile strategy/
          docker push $DOCKER_IMAGE_PREFIX/strategy:latest
          
          docker build -t $DOCKER_IMAGE_PREFIX/risk-management:latest -f risk-management/Dockerfile risk-management/
          docker push $DOCKER_IMAGE_PREFIX/risk-management:latest
          
          docker build -t $DOCKER_IMAGE_PREFIX/visualization:latest -f visualization/Dockerfile visualization/
          dock
