name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Ensures the job runs on your self-hosted runner

    steps:
      # Step 1: Install PowerShell Core
      - name: Install PowerShell Core
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell

      # Step 2: Set PowerShell Execution Policy (now `pwsh` is available)
      - name: Set PowerShell Execution Policy
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
      
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker images
      - name: Build and push Docker images
        env:
          DOCKER_IMAGE_PREFIX: your_dockerhub_username
        run: |
          docker build -t $DOCKER_IMAGE_PREFIX/data-ingestion:latest -f data-ingestion/Dockerfile data-ingestion/
          docker push $DOCKER_IMAGE_PREFIX/data-ingestion:latest
          
          docker build -t $DOCKER_IMAGE_PREFIX/strategy:latest -f strategy/Dockerfile strategy/
          docker push $DOCKER_IMAGE_PREFIX/strategy:latest
          
          docker build -t $DOCKER_IMAGE_PREFIX/risk-management:latest -f risk-management/Dockerfile risk-management/
          docker push $DOCKER_IMAGE_PREFIX/risk-management:latest
          
          docker build -t $DOCKER_IMAGE_PREFIX/visualization:latest -f visualization/Dockerfile visualization/
          docker push $DOCKER_IMAGE_PREFIX/visualization:latest

      # Step 5: Set up kubeconfig (if necessary)
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > ~/.kube/config
        shell: bash

      # Step 6: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ~/.kube/config
        run: |
          kubectl apply -f k8s-deployment.yaml
