name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Or windows-latest if you're using a Windows runner

    steps:
      # Step 1: Temporarily set PowerShell execution policy
      - name: Set PowerShell Execution Policy
        shell: cmd
        run: |
          powershell.exe -Command "Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force"


      

      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker images without using DOCKER_IMAGE_PREFIX
      - name: Build and push Docker images
        shell: powershell  # Use `powershell` if on a Windows runner
        run: |
          # Replace `your_dockerhub_username` with your actual Docker Hub username
          docker build -t khalilamouri/data-ingestion:latest -f data-ingestion/Dockerfile data-ingestion/
          docker push khalilamouri/data-ingestion:latest
          
          docker build -t khalilamouri/strategy:latest -f strategy/Dockerfile strategy/
          docker push khalilamouri/strategy:latest
          
          docker build -t khalilamouri/risk-management:latest -f risk-management/Dockerfile risk-management/
          docker push khalilamouri/risk-management:latest
          
          docker build -t khalilamouri/visualization:latest -f visualization/Dockerfile visualization/
          docker push khalilamouri/visualization:latest

      # Optional Step 4: Set up kubeconfig if deploying to Kubernetes
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > ~/.kube/config
        shell: bash

      # Optional Step 5: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ~/.kube/config
        run: |
          kubectl apply -f k8s-deployment.yaml
