name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker images
      - name: Build and push Docker images
        env:
          DOCKER_IMAGE_PREFIX: khalilamouri  # Updated Docker Hub username
        run: |
          docker build -t $DOCKER_IMAGE_PREFIX/data-ingestion:latest -f data-ingestion/Dockerfile data-ingestion/
          docker push $DOCKER_IMAGE_PREFIX/data-ingestion:latest
          
          docker build -t $DOCKER_IMAGE_PREFIX/strategy:latest -f strategy/Dockerfile strategy/
          docker push $DOCKER_IMAGE_PREFIX/strategy:latest
          
          docker build -t $DOCKER_IMAGE_PREFIX/risk-management:latest -f risk-management/Dockerfile risk-management/
          docker push $DOCKER_IMAGE_PREFIX/risk-management:latest
          
          docker build -t $DOCKER_IMAGE_PREFIX/visualization:latest -f visualization/Dockerfile visualization/
          docker push $DOCKER_IMAGE_PREFIX/visualization:latest

      # Step 5: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s-deployment.yaml
