name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Or windows-latest if you're using a Windows runner

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub (Directly in cmd)
      - name: Log in to Docker Hub
        shell: cmd
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker images (Directly in cmd)
      - name: Build and push Docker images
        shell: cmd
        run: |
          # Replace `your_dockerhub_username` with your actual Docker Hub username
          docker build -t your_dockerhub_username/data-ingestion:latest -f data-ingestion/Dockerfile data-ingestion/
          docker push your_dockerhub_username/data-ingestion:latest
          
          docker build -t your_dockerhub_username/strategy:latest -f strategy/Dockerfile strategy/
          docker push your_dockerhub_username/strategy:latest
          
          docker build -t your_dockerhub_username/risk-management:latest -f risk-management/Dockerfile risk-management/
          docker push your_dockerhub_username/risk-management:latest
          
          docker build -t your_dockerhub_username/visualization:latest -f visualization/Dockerfile visualization/
          docker push your_dockerhub_username/visualization:latest

      # Optional Step 4: Set up kubeconfig if deploying to Kubernetes
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > ~/.kube/config
        shell: bash

      # Optional Step 5: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ~/.kube/config
        run: |
          kubectl apply -f k8s-deployment.yaml
